// Full browser + signed JWT/PostgREST + Realtime test. Always removes fixtures in finally.
import assert from 'node:assert/strict'
import { createClient } from '@supabase/supabase-js'
import { chromium, expect as baseExpect } from '../.verification.local/node_modules/@playwright/test/index.mjs'
import { realFixtures, checked, project, url } from './crm-real-fixtures.mjs'

const expect = baseExpect.configure({ timeout: 15000 })
const origin = process.env.CRM_TEST_ORIGIN || 'http://127.0.0.1:5198'
if (!['127.0.0.1', 'localhost'].includes(new URL(origin).hostname)) throw Error('CRM fixture UI tests may run only against a local frontend connected to staging')
const future = days => {
  const date = new Date(Date.now() + days * 86400000)
  return new Date(+date - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16)
}
await realFixtures(async ({ clients, sessions, users, anon, name, productId, ticketId }) => {
  const browser = await chromium.launch({ channel: 'chromium', headless: true })
  const errors = [], unexpected = []
  let page
  const actor = role => users.find(u => u.fixtureRole === role).id
  const leadBy = async id => checked(clients.seller.from('crm_leads').select('*').eq('id', id).single())
  const act = (role, lead, action, data = {}) => checked(clients[role].rpc('crm_transition', { p_lead_id: lead.id, p_action: action, p_expected_version: lead.version, p_data: data }))
  const openCardAction = async (tab, card, name) => {
    await card.getByRole('button', { name: /^Ações de / }).click()
    await tab.getByRole('menuitem', { name, exact: true }).click()
  }
  const session = async (role, viewport = { width: 1440, height: 1080 }) => {
    const context = await browser.newContext({ viewport })
    if (role === 'second') await context.addInitScript(() => {
      // Disable only polling intervals; keep React Query notification timers and socket heartbeats.
      const interval = window.setInterval.bind(window)
      window.setInterval = (callback, delay, ...args) => interval(callback, delay === 15000 || delay === 30000 ? 3600000 : delay, ...args)
    })
    await context.addInitScript(({ project, session }) => {
      if (!sessionStorage.getItem(`sb-${project}-auth-token`)) sessionStorage.setItem(`sb-${project}-auth-token`, JSON.stringify(session))
    }, { project, session: sessions[role] })
    const tab = await context.newPage()
    tab.on('pageerror', error => errors.push(error.message))
    tab.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
    tab.on('response', response => { if (response.status() >= 400) unexpected.push(`${response.status()} ${new URL(response.url()).pathname}`) })
    await tab.goto(`${origin}/crm`)
    return tab
  }
  try {
    for (const [role, expected] of Object.entries({ seller: [true,true,true,false], second: [true,true,true,false], executive: [true,true,true,true], sdr: [true,true,false,false], closer: [true,false,true,false], blocked: [false,false,false,false], suspended: [false,false,false,false] })) {
      for (const [i, capability] of ['leads', 'sdr', 'closer', 'admin'].entries()) assert.equal(await checked(clients[role].rpc('crm_can', { p_capability: capability })), expected[i], `${role} ${capability}`)
    }
    assert.ok((await clients.seller.rpc('executive_list_users')).error, 'seller user-directory access')
    assert.ok(await checked(clients.executive.rpc('executive_list_users')))
    const anonymous = createClient(url, anon, { auth: { persistSession: false } })
    assert.ok((await anonymous.rpc('crm_transition', { p_lead_id: actor('seller'), p_action: 'claim', p_expected_version: 1 })).error, 'anonymous RPC')
    const anonLeads = await anonymous.from('crm_leads').select('id').limit(1)
    assert.ok(anonLeads.error || anonLeads.data.length === 0, 'anonymous RLS disclosed leads')

    page = await session('seller')
    await expect(page.getByRole('tab', { name: 'SDR', exact: true })).toBeVisible()
    await expect(page.getByRole('tab', { name: 'Closer', exact: true })).toBeVisible()
    await expect(page.getByRole('tab', { name: 'Gerenciar Usuários', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Novo Lead', exact: true }).click()
    let dialog = page.getByRole('dialog', { name: 'Novo Lead', exact: true })
    await expect(dialog.getByLabel('E-mail (opcional)', { exact: true })).not.toHaveAttribute('required', '')
    await dialog.getByLabel('Nome do responsável *', { exact: true }).fill(name)
    await dialog.getByLabel('Nome do atleta *', { exact: true }).fill(`${name} Atleta`)
    await dialog.getByLabel('WhatsApp *', { exact: true }).fill('11999999999')
    await dialog.getByRole('button', { name: 'Criar Lead', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await page.getByLabel('Buscar leads', { exact: true }).fill(name)
    let card = page.getByRole('article', { name: `Lead ${name}`, exact: true })
    await expect(card).toBeVisible()
    let lead = (await checked(clients.seller.from('crm_leads').select('*').eq('created_by', actor('seller')).eq('name', name)))[0]
    assert.ok(lead)
    assert.equal(lead.email, null); assert.equal(lead.athlete_birth_date, null); assert.equal(lead.athlete_position, null)
    assert.equal(lead.pipeline_stage, 'novo')
    const leadId = lead.id
    await card.getByRole('button', { name: `Editar ${name}`, exact: true }).click()
    dialog = page.getByRole('dialog', { name: 'Editar lead', exact: true })
    await expect(dialog.getByLabel('Nome do responsável *', { exact: true })).toHaveValue(name)
    await dialog.getByLabel('Cidade / UF', { exact: true }).fill('São Paulo / SP')
    await dialog.getByRole('button', { name: 'Salvar cadastro', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    assert.equal((await leadBy(leadId)).city_state, 'São Paulo / SP')
    await card.getByRole('button', { name: `Abrir ficha de ${name}`, exact: true }).click()
    const sheet = page.getByRole('dialog', { name: `Ficha de ${name}`, exact: true })
    await expect(sheet.getByText('São Paulo / SP', { exact: true })).toBeVisible()
    await expect(sheet.getByRole('heading', { name: 'Histórico do lead', exact: true })).toBeVisible()
    await sheet.getByRole('button', { name: 'Close', exact: true }).click()
    await page.getByRole('tab', { name: 'SDR', exact: true }).click()
    await page.getByLabel(`Aquecimento de ${name}`, { exact: true }).selectOption('quente')
    await expect.poll(async () => (await leadBy(leadId)).temperature).toBe('quente')
    for (const stage of ['em_abordagem', 'abordado', 'reabordado', 'nao_abordado', 'abordado']) {
      await page.getByLabel(`Abordagem de ${name}`, { exact: true }).selectOption(stage)
      await expect.poll(async () => (await leadBy(leadId)).approach_stage).toBe(stage)
      await expect(card.getByRole('button', { name: 'Agendar call e enviar', exact: true })).toBeEnabled()
    }
    lead = await leadBy(leadId)
    assert.equal(lead.pipeline_stage, 'pronto_closer')
    assert.ok((await clients.seller.from('crm_leads').update({ pipeline_stage: 'novo' }).eq('id', leadId)).error, 'direct pipeline accepted')
    await openCardAction(page, card, 'Registrar contato/anotação')
    dialog = page.getByRole('dialog', { name: 'Registrar contato/anotação', exact: true })
    await dialog.getByLabel('Anotação', { exact: true }).fill('QA: contato estabelecido antes do agendamento e repasse.')
    await dialog.getByRole('button', { name: 'Confirmar', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    const second = await session('second')
    await second.getByRole('tab', { name: 'Closer', exact: true }).click()
    await second.getByLabel('Buscar leads', { exact: true }).fill(name)
    const secondCard = second.getByRole('article', { name: `Lead ${name}`, exact: true })
    await expect(secondCard).toHaveCount(0)
    let realtimeEvent
    const realtime = clients.second.channel(`crm-qa-${leadId}`).on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'crm_leads', filter: `id=eq.${leadId}` }, payload => { realtimeEvent = payload.new })
    await clients.second.realtime.setAuth(sessions.second.access_token)
    await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(Error('Realtime subscription timeout')), 15000)
      realtime.subscribe(status => { if (status === 'SUBSCRIBED') { clearTimeout(timer); resolve() } else if (status === 'CHANNEL_ERROR') { clearTimeout(timer); reject(Error('Realtime subscription failed')) } })
    })
    // This session has polling disabled, so cross-session UI update proves Realtime.
    await card.getByRole('button', { name: 'Agendar call e enviar', exact: true }).click()
    dialog = page.getByRole('dialog', { name: 'Agendar call e enviar ao Closer', exact: true })
    await expect(dialog.getByLabel('Responsável', { exact: true })).toHaveValue('')
    await dialog.getByLabel('Responsável', { exact: true }).selectOption(actor('second'))
    await dialog.getByLabel('Data e hora (horário local)', { exact: true }).fill(future(1))
    await dialog.getByLabel('Contexto da reunião', { exact: true }).fill('QA: contexto enviado automaticamente pelo SDR.')
    // Opening/filling the scheduler must not hand off before the save succeeds.
    await expect(secondCard).toHaveCount(0)
    await dialog.getByRole('button', { name: 'Agendar e enviar', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await expect.poll(() => realtimeEvent?.pipeline_stage).toBe('repassado_closer')
    await expect(secondCard).toBeVisible()
    assert.equal((await leadBy(leadId)).id, leadId)
    await expect(secondCard.getByRole('button', { name: 'Registrar fechamento', exact: true })).toBeVisible()
    const callStatus = secondCard.getByLabel(/^Call agendada para /)
    await expect(callStatus).toBeVisible()
    await expect(callStatus.getByText(/^Data: /)).toBeVisible()
    await expect(callStatus.getByText(/^Horário: /)).toBeVisible()
    lead = await leadBy(leadId)
    assert.equal(lead.closer_id, actor('second'))
    const synchronizedCall = (await checked(clients.seller.from('crm_activities').select('*').eq('lead_id', leadId).eq('call_type', 'fechamento_closer').eq('is_completed', false).single()))
    assert.equal(synchronizedCall.assigned_to, actor('second'))
    assert.equal(synchronizedCall.scheduled_at, lead.next_followup_at)
    assert.equal(synchronizedCall.description, 'QA: contexto enviado automaticamente pelo SDR.')
    assert.ok((await clients.seller.rpc('crm_transition', { p_lead_id: leadId, p_action: 'close', p_expected_version: lead.version, p_data: { outcome: 'venda_concluida' } })).error, 'non-owner closing')
    await openCardAction(second, secondCard, 'Reagendar call')
    dialog = second.getByRole('dialog', { name: 'Reagendar call', exact: true })
    await dialog.getByLabel('Data e hora (horário local)', { exact: true }).fill(future(2))
    await dialog.getByRole('button', { name: 'Salvar horário', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await second.screenshot({ path: '.verification.local/crm-real-desktop.png', fullPage: true })
    await second.setViewportSize({ width: 390, height: 844 })
    await second.screenshot({ path: '.verification.local/crm-real-mobile.png', fullPage: true })
    assert.equal(await second.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, '390px horizontal overflow')
    await secondCard.getByRole('button', { name: 'Registrar fechamento', exact: true }).click()
    dialog = second.getByRole('dialog', { name: 'Registrar fechamento', exact: true })
    await dialog.getByLabel('Resultado *', { exact: true }).selectOption('followup')
    await expect(dialog.getByLabel('Próxima data e hora *', { exact: true })).toBeVisible()
    await dialog.getByLabel('Próxima data e hora *', { exact: true }).fill(future(3))
    await dialog.getByLabel('Observações da call', { exact: true }).fill('QA: família pediu acompanhamento.')
    await dialog.getByRole('button', { name: 'Confirmar', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    assert.equal((await leadBy(leadId)).pipeline_stage, 'repassado_closer')
    await secondCard.getByRole('button', { name: 'Registrar fechamento', exact: true }).click()
    dialog = second.getByRole('dialog', { name: 'Registrar fechamento', exact: true })
    await dialog.getByLabel('Resultado *', { exact: true }).selectOption('venda_concluida')
    await dialog.getByRole('button', { name: 'Confirmar', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await second.getByRole('tab', { name: /Fechamentos realizados/ }).click()
    await expect(secondCard.getByText('Venda pendente de cadastro', { exact: true })).toBeVisible()
    assert.equal((await checked(clients.second.from('vendas').select('id').eq('crm_lead_id', leadId))).length, 0)
    await second.reload()
    await second.getByRole('tab', { name: /Fechamentos realizados/ }).click()
    await second.getByLabel('Buscar leads', { exact: true }).fill(name)
    await expect(secondCard.getByText('Venda pendente de cadastro', { exact: true })).toBeVisible()
    await secondCard.getByRole('button', { name: 'Cadastrar venda no módulo Vendas', exact: true }).click()
    await expect(second.getByLabel('Nome Do Comprador *', { exact: true })).toHaveValue(name)
    await expect(second.getByLabel('WhatsApp Do Comprador *', { exact: true })).toHaveValue('11999999999')
    await expect(second.getByLabel('Email Do Comprador *', { exact: true })).toHaveValue('')
    await second.getByLabel('Email Do Comprador *', { exact: true }).fill('qa-buyer@example.invalid')
    await second.getByRole('combobox', { name: 'Nome Do Produto Vendido *', exact: true }).click()
    await second.getByRole('option', { name: `${name} Produto`, exact: true }).click()
    await second.getByRole('combobox', { name: 'Ticket e valor da venda *', exact: true }).click()
    await second.getByRole('option', { name: /QA Ticket/ }).click()
    await second.getByRole('button', { name: 'Registrar Venda', exact: true }).click()
    await expect(second.getByText('Venda registrada! Aguardando aprovação', { exact: true })).toBeVisible()
    const sale = (await checked(clients.second.from('vendas').select('*').eq('crm_lead_id', leadId)))[0]
    assert.equal(sale.user_id, actor('second')); assert.equal(sale.product_id, productId); assert.equal(sale.ticket_id, ticketId)
    await second.goto(`${origin}/crm?tab=closer`)
    await second.getByRole('tab', { name: /Fechamentos realizados/ }).click()
    await second.getByLabel('Buscar leads', { exact: true }).fill(name)
    await expect(secondCard.getByText('Venda cadastrada', { exact: true })).toBeVisible()
    await secondCard.getByRole('button', { name: 'Abrir venda cadastrada', exact: true }).click()
    await expect(second.getByRole('dialog', { name: 'Venda cadastrada', exact: true }).getByText(name, { exact: true })).toBeVisible()
    await clients.second.removeChannel(realtime)

    // Real API race: one action wins; the other gets a clear version conflict.
    let race = await checked(clients.seller.from('crm_leads').insert({ name: `${name} Race`, athlete_name: 'QA Race Atleta', phone: '11999999999' }).select().single())
    const results = await Promise.all(['morno','quente'].map(temperature => clients.seller.rpc('crm_transition', { p_lead_id: race.id, p_action: 'classify', p_expected_version: race.version, p_data: { temperature } })))
    assert.equal(results.filter(r => !r.error).length, 1); assert.equal(results.filter(r => r.error?.code === 'PT409').length, 1)
    race = await leadBy(race.id)
    race = await act('seller', race, 'handoff', { closer_id: actor('second') })
    race = await act('second', race, 'return', { note: 'QA devolução ao SDR' })
    assert.equal(race.pipeline_stage, 'em_qualificacao')
    race = await act('seller', race, 'handoff', { closer_id: actor('second') })
    race = await act('second', race, 'close', { outcome: 'venda_perdida' })
    assert.equal(race.pipeline_stage, 'fechado_perdido')
    for (const role of ['blocked', 'suspended']) {
      assert.equal((await checked(clients[role].from('crm_leads').select('id').eq('id', leadId))).length, 0)
      assert.ok((await clients[role].rpc('crm_transition', { p_lead_id: leadId, p_action: 'claim', p_expected_version: 1 })).error)
    }
    for (const role of ['sdr','closer','executive']) {
      const tab = await session(role)
      await expect(tab.getByRole('tab', { name: role === 'closer' ? 'Closer' : 'SDR', exact: true })).toBeVisible()
      if (role !== 'executive') await expect(tab.getByRole('tab', { name: role === 'closer' ? 'SDR' : 'Closer', exact: true })).toHaveCount(0)
      else {
        await tab.getByRole('tab', { name: 'Relatório de Permissões', exact: true }).click()
        await expect(tab.getByLabel('Buscar usuário no relatório', { exact: true })).toBeVisible()
        await tab.getByRole('tab', { name: 'Gerenciar Usuários', exact: true }).click()
        await expect(tab.getByPlaceholder(/Buscar/).first()).toBeVisible()
      }
      await tab.context().close()
    }
    await page.goto(`${origin}/crm?tab=users`)
    await expect(page.getByText('Sua função não permite acessar esta área.', { exact: false })).toBeVisible()
    const suspended = await session('suspended')
    await expect(suspended).toHaveURL(/\/auth/)
    await suspended.context().close()
    const publicTab = await browser.newPage()
    await publicTab.goto(`${origin}/crm`)
    await expect(publicTab).toHaveURL(/\/auth/)
    await publicTab.close()
    assert.deepEqual(unexpected, [], `Unexpected HTTP failures: ${unexpected.join('; ')}`)
    assert.deepEqual(errors, [], `Browser errors: ${errors.join('; ')}`)
    console.log('PASS: real JWT/PostgREST permissions, minimal create/edit, four approach states, pipeline, immutable history, schedule-before-handoff, synchronized SDR/Closer data, Realtime across sessions without timers/reload, rescheduling, follow-up, win/loss/return, persistent CTA, catalog/manual sale ownership and linkage, concurrency, admin guards, 1440/390px and browser console/HTTP checks.')
  } catch (error) {
    if (page && !page.isClosed()) await page.screenshot({ path: '.verification.local/crm-real-failure.png', fullPage: true })
    throw error
  } finally { await browser.close() }
})
